// CASSANDRA PLANNING — app.js
let currentYear=new Date().getFullYear(),currentMonth=new Date().getMonth();
let clients=[],rdvs=[],collabs=[];
let editRdvId=null,editClientId=null,editCollabId=null,detailClientId=null;
let currentRec='none',selectedCollabs=[],selectedColor='#1a3a5c';
const PALETTE=['#1a3a5c','#2e7d32','#b71c1c','#6a1b9a','#e65100','#00695c','#4527a0','#c62828','#1565c0','#37474f'];
const MONTHS=['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
const TYPES={regulier:'Ménage régulier',ponctuel:'Ménage ponctuel',vitre:'Vitres',repassage:'Repassage',autre:'Autre'};
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function fmt(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function pad(n){return String(n).padStart(2,'0')}
function fmtDate(s){if(!s)return'';const[y,m,d]=s.split('-');return d+'/'+m+'/'+y}
function addDays(s,n){const d=new Date(s);d.setDate(d.getDate()+n);return fmt(d)}
function hexRgb(h){return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)].join(',')}
function alpha(h,a){return 'rgba('+hexRgb(h)+','+a+')'}
function hFmt(v){return v%1===0?v+'h':v.toFixed(1)+'h'}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function login(){
  const name=document.getElementById('login-name').value.trim();
  const pass=document.getElementById('login-pass').value;
  const err=document.getElementById('login-error');
  const match=collabs.find(c=>c.password===pass&&c.prenom.toLowerCase()===name.toLowerCase());
  const isAdmin=pass==='admin2025';
  if(!match&&!isAdmin){err.textContent='Prénom ou mot de passe incorrect.';return}
  currentUser=match||{prenom:name,color:'#1a3a5c',role:'associe'};
  document.getElementById('login-screen').classList.add('hidden');
  document.getElementById('app').classList.remove('hidden');
  document.getElementById('user-name-display').textContent=currentUser.prenom;
  document.getElementById('user-avatar').textContent=currentUser.prenom[0].toUpperCase();
  localStorage.setItem('cp_user',JSON.stringify(currentUser));
  err.textContent='';
  renderCal();
}
function logout(){localStorage.removeItem('cp_user');currentUser=null;document.getElementById('app').classList.add('hidden');document.getElementById('login-screen').classList.remove('hidden');document.getElementById('login-pass').value=''}
function showTab(t,btn){document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+t).classList.add('active');if(t==='clients')renderClients();if(t==='rdvlist')renderRdvList();if(t==='collaborateurs')renderCollabs()}
function closeModal(id){document.getElementById(id).classList.remove('open')}
function overlayClose(e,id){if(e.target===document.getElementById(id))closeModal(id)}
function setRec(val,btn){currentRec=val;document.querySelectorAll('.rec-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.getElementById('rec-until-box').style.display=val==='none'?'none':'block';if(val!=='none'&&!document.getElementById('rdv-until').value){const d=new Date();d.setMonth(d.getMonth()+3);document.getElementById('rdv-until').value=fmt(d)}}
function getVisibleRdvs(){const singles=rdvs.filter(r=>!r.seriesId&&!r.cancelled);const expanded=[];rdvs.filter(r=>r.seriesId&&r.isFirst).forEach(r=>{const step=r.recurrence==='1w'?7:14;let cur=r.date,idx=0;while(cur<=r.until){const cancelled=rdvs.find(x=>x.seriesId===r.seriesId&&x.date===cur&&x.cancelled);if(!cancelled)expanded.push({...r,id:r.id+'_'+idx,_vDate:cur,_pid:r.id});cur=addDays(cur,step);idx++}});return[...singles,...expanded]}
function getStats(){const all=getVisibleRdvs();const mStr=currentYear+'-'+pad(currentMonth+1);const mRdv=all.filter(r=>(r._vDate||r.date).startsWith(mStr));const clientIds=new Set(mRdv.map(r=>r.clientId));const totalH=mRdv.reduce((s,r)=>s+parseFloat(r.duree||2),0);const byCollab={};mRdv.forEach(r=>{(r.collabs||[]).forEach(cid=>{byCollab[cid]=(byCollab[cid]||0)+parseFloat(r.duree||2)})});return{nb:mRdv.length,clients:clientIds.size,hours:totalH,byCollab}}
function renderStats(){const s=getStats();document.getElementById('stats-row').innerHTML='<div class="stat-card"><div class="stat-label">Interventions</div><div class="stat-value">'+s.nb+'</div><div class="stat-sub">ce mois</div></div><div class="stat-card"><div class="stat-label">Clients actifs</div><div class="stat-value">'+s.clients+'</div><div class="stat-sub">clients distincts</div></div><div class="stat-card"><div class="stat-label">Heures totales</div><div class="stat-value">'+hFmt(s.hours)+'</div><div class="stat-sub">sur le mois</div></div><div class="stat-card"><div class="stat-label">Mois en cours</div><div class="stat-value" style="font-size:18px;padding-top:4px">'+MONTHS[currentMonth]+'</div><div class="stat-sub">'+currentYear+'</div></div>';let leg='';collabs.forEach(c=>{const h=s.byCollab[c.id]||0;leg+='<div class="leg-item"><div class="leg-dot" style="background:'+c.color+'"></div><span>'+c.prenom+'</span><span class="leg-hours" style="background:'+alpha(c.color,0.12)+';color:'+c.color+'">'+( h>0?hFmt(h):'—')+'</span></div>'});leg+='<div class="leg-item"><span class="leg-rec">↻ récurrent</span></div>';document.getElementById('legend-row').innerHTML=leg}
function prevMonth(){currentMonth--;if(currentMonth<0){currentMonth=11;currentYear--}renderCal()}
function nextMonth(){currentMonth++;if(currentMonth>11){currentMonth=0;currentYear++}renderCal()}
function renderCal(){const label=MONTHS[currentMonth]+' '+currentYear;document.getElementById('month-label').textContent=label;document.getElementById('month-desc').textContent=label;const grid=document.getElementById('cal-grid');grid.innerHTML='';const first=new Date(currentYear,currentMonth,1);const last=new Date(currentYear,currentMonth+1,0);const startDay=(first.getDay()+6)%7;const today=new Date();const todayStr=fmt(today);const cells=[];for(let i=0;i<startDay;i++)cells.push({date:new Date(currentYear,currentMonth,1-startDay+i),other:true});for(let d=1;d<=last.getDate();d++)cells.push({date:new Date(currentYear,currentMonth,d),other:false});while(cells.length%7!==0)cells.push({date:new Date(currentYear,currentMonth+1,cells.length-last.getDate()-startDay+1),other:true});const visible=getVisibleRdvs();cells.forEach(c=>{const div=document.createElement('div');const dateStr=fmt(c.date);const isToday=dateStr===todayStr;const isWE=c.date.getDay()===0||c.date.getDay()===6;div.className='cal-day'+(c.other?' other-month':'')+(isToday?' today':'')+(isWE?' weekend':'');const numEl=document.createElement('div');if(isToday){numEl.innerHTML='<div class="day-num today-circle">'+c.date.getDate()+'</div>'}else{numEl.className='day-num';numEl.textContent=c.date.getDate()}div.appendChild(numEl);const dayRdvs=visible.filter(r=>(r._vDate||r.date)===dateStr).sort((a,b)=>a.time.localeCompare(b.time));const MAX_SHOW=3;dayRdvs.slice(0,MAX_SHOW).forEach(r=>{const cl=clients.find(x=>x.id===r.clientId);const co=collabs.find(x=>(r.collabs||[]).includes(x.id));const col=co?.color||'#888780';const pill=document.createElement('div');pill.className='rdv-pill';pill.style.background=alpha(col,0.13);pill.style.color=col;pill.style.borderLeft='2px solid '+col;let inner='';if(r.seriesId)inner+='<span class="rec-dot">↻</span>';inner+='<span style="overflow:hidden;text-overflow:ellipsis">'+r.time+(cl?' '+cl.prenom:'')+'</span>';if((r.collabs||[]).length>1)inner+='<span class="multi-badge">+'+(r.collabs.length-1)+'</span>';pill.innerHTML=inner;pill.onclick=()=>openEditRdv(r._pid||r.id,r._vDate||r.date);div.appendChild(pill)});if(dayRdvs.length>MAX_SHOW){const more=document.createElement('div');more.className='more-pill';more.textContent='+'+(dayRdvs.length-MAX_SHOW)+' autre'+(dayRdvs.length-MAX_SHOW>1?'s':'');div.appendChild(more)}div.addEventListener('dblclick',()=>openNewRdv(dateStr));grid.appendChild(div)});renderStats()}
function buildCollabChips(selected){selectedCollabs=[...selected];const box=document.getElementById('collab-assign');box.innerHTML='';if(!collabs.length){box.innerHTML='<span style="font-size:12px;color:#aaa">Ajoutez d'abord des collaborateurs</span>';return}collabs.forEach(c=>{const isSel=selectedCollabs.includes(c.id);const chip=document.createElement('div');chip.className='chip-btn';chip.style.background=isSel?alpha(c.color,0.15):'var(--surface2)';chip.style.color=isSel?c.color:'var(--text2)';chip.style.borderColor=isSel?alpha(c.color,0.5):'var(--border)';chip.innerHTML='<span style="width:8px;height:8px;border-radius:50%;background:'+c.color+';display:inline-block"></span>'+c.prenom;chip.onclick=()=>{if(selectedCollabs.includes(c.id))selectedCollabs=selectedCollabs.filter(x=>x!==c.id);else selectedCollabs.push(c.id);buildCollabChips(selectedCollabs)};box.appendChild(chip)})}
function openNewRdv(date){editRdvId=null;currentRec='none';document.getElementById('rdv-modal-title').textContent='Nouveau rendez-vous';document.getElementById('rdv-client').innerHTML=clients.length?clients.map(c=>'<option value="'+c.id+'">'+c.prenom+' '+c.nom+'</option>').join(''):'<option value="">— Aucun client —</option>';document.getElementById('rdv-date').value=date||fmt(new Date());document.getElementById('rdv-time').value='09:00';document.getElementById('rdv-duree').value='2';document.getElementById('rdv-type').value='regulier';document.getElementById('rdv-note').value='';document.getElementById('rdv-until').value='';document.getElementById('rec-until-box').style.display='none';document.querySelectorAll('.rec-btn').forEach((b,i)=>b.classList.toggle('active',i===0));document.getElementById('rdv-delete-btn').style.display='none';document.getElementById('delete-scope-box').style.display='none';buildCollabChips([]);document.getElementById('modal-rdv').classList.add('open')}
function openEditRdv(id,virtualDate){const r=rdvs.find(x=>x.id===id);if(!r)return;editRdvId=id;currentRec=r.recurrence||'none';document.getElementById('rdv-modal-title').textContent='Modifier le rendez-vous';document.getElementById('rdv-client').innerHTML=clients.map(c=>'<option value="'+c.id+'">'+c.prenom+' '+c.nom+'</option>').join('');document.getElementById('rdv-client').value=r.clientId;document.getElementById('rdv-date').value=virtualDate||r.date;document.getElementById('rdv-time').value=r.time;document.getElementById('rdv-duree').value=r.duree;document.getElementById('rdv-type').value=r.type||'regulier';document.getElementById('rdv-note').value=r.note||'';document.getElementById('rdv-until').value=r.until||'';document.getElementById('rec-until-box').style.display=currentRec==='none'?'none':'block';document.querySelectorAll('.rec-btn').forEach((b,i)=>b.classList.toggle('active',['none','1w','2w'][i]===currentRec));document.getElementById('rdv-delete-btn').style.display='inline-flex';document.getElementById('delete-scope-box').style.display=r.seriesId?'block':'none';document.querySelector('input[name="del-scope"][value="one"]').checked=true;buildCollabChips(r.collabs||[]);document.getElementById('modal-rdv').classList.add('open')}
async function saveRdv(){const clientId=document.getElementById('rdv-client').value;const date=document.getElementById('rdv-date').value;const time=document.getElementById('rdv-time').value;if(!date||!time){toast('Date et heure obligatoires');return}const base={clientId,date,time,duree:document.getElementById('rdv-duree').value,type:document.getElementById('rdv-type').value,note:document.getElementById('rdv-note').value,collabs:[...selectedCollabs]};if(editRdvId){await window.DB.remove('rdvs',editRdvId);rdvs=rdvs.filter(r=>r.id!==editRdvId)}const id=uid();if(currentRec==='none'){const obj={...base,id};await window.DB.save('rdvs',id,obj)}else{const until=document.getElementById('rdv-until').value||addDays(date,90);const seriesId=uid();const obj={...base,id,seriesId,recurrence:currentRec,until,isFirst:true};await window.DB.save('rdvs',id,obj)}toast('Rendez-vous enregistré ✓');closeModal('modal-rdv')}
async function deleteRdv(){const r=rdvs.find(x=>x.id===editRdvId);if(!r)return closeModal('modal-rdv');if(!r.seriesId){if(!confirm('Supprimer ?'))return;await window.DB.remove('rdvs',editRdvId);toast('Supprimé');return closeModal('modal-rdv')}const scope=document.querySelector('input[name="del-scope"]:checked').value;const curDate=document.getElementById('rdv-date').value;if(scope==='one'){const cid=uid();await window.DB.save('rdvs',cid,{id:cid,seriesId:r.seriesId,date:curDate,cancelled:true})}else if(scope==='future'){const newUntil=addDays(curDate,r.recurrence==='1w'?-7:-14);await window.DB.save('rdvs',editRdvId,{...r,until:newUntil})}else{const toDelete=rdvs.filter(x=>x.id===editRdvId||x.seriesId===r.seriesId);await Promise.all(toDelete.map(x=>window.DB.remove('rdvs',x.id)))}toast('Supprimé');closeModal('modal-rdv')}
function openNewClient(){editClientId=null;document.getElementById('client-modal-title').textContent='Nouveau client';['cl-prenom','cl-nom','cl-email','cl-tel','cl-adresse','cl-contrat','cl-note'].forEach(id=>document.getElementById(id).value='');document.getElementById('cl-type').value='particulier';document.getElementById('cl-delete-btn').style.display='none';document.getElementById('modal-client').classList.add('open')}
function openEditClient(id){const c=clients.find(x=>x.id===id);if(!c)return;editClientId=id;document.getElementById('client-modal-title').textContent='Modifier le client';document.getElementById('cl-prenom').value=c.prenom||'';document.getElementById('cl-nom').value=c.nom||'';document.getElementById('cl-email').value=c.email||'';document.getElementById('cl-tel').value=c.tel||'';document.getElementById('cl-adresse').value=c.adresse||'';document.getElementById('cl-type').value=c.type||'particulier';document.getElementById('cl-contrat').value=c.contrat||'';document.getElementById('cl-note').value=c.note||'';document.getElementById('cl-delete-btn').style.display='inline-flex';document.getElementById('modal-client').classList.add('open')}
function editClientFromDetail(){closeModal('modal-client-detail');openEditClient(detailClientId)}
async function saveClient(){const prenom=document.getElementById('cl-prenom').value.trim();const nom=document.getElementById('cl-nom').value.trim();if(!prenom&&!nom){toast('Nom obligatoire');return}const id=editClientId||uid();const cl={id,prenom,nom,email:document.getElementById('cl-email').value.trim(),tel:document.getElementById('cl-tel').value.trim(),adresse:document.getElementById('cl-adresse').value.trim(),type:document.getElementById('cl-type').value,contrat:document.getElementById('cl-contrat').value,note:document.getElementById('cl-note').value.trim()};await window.DB.save('clients',id,cl);toast('Client enregistré ✓');closeModal('modal-client')}
async function deleteClient(){if(!confirm('Supprimer ce client ?'))return;await window.DB.remove('clients',editClientId);toast('Client supprimé');closeModal('modal-client')}
function showClientDetail(id){const c=clients.find(x=>x.id===id);if(!c)return;detailClientId=id;document.getElementById('detail-nom').textContent=c.prenom+' '+c.nom;const nb=getVisibleRdvs().filter(r=>r.clientId===id).length;const typeTag=c.type==='pro'?'<span class="badge" style="background:#e8f0f8;color:#1a3a5c">Pro</span>':'<span class="badge" style="background:#e8f5e9;color:#2e7d32">Particulier</span>';document.getElementById('detail-body').innerHTML='<div class="info-row"><span class="info-lbl">Type</span>'+typeTag+'</div>'+(c.email?'<div class="info-row"><span class="info-lbl">Email</span><span>'+c.email+'</span></div>':'')+(c.tel?'<div class="info-row"><span class="info-lbl">Téléphone</span><span>'+c.tel+'</span></div>':'')+(c.adresse?'<div class="info-row"><span class="info-lbl">Adresse</span><span>'+c.adresse+'</span></div>':'')+(c.contrat?'<div class="info-row"><span class="info-lbl">Contrat signé</span><span>'+fmtDate(c.contrat)+'</span></div>':'')+'<div class="info-row"><span class="info-lbl">Rendez-vous</span><span>'+nb+' planifiés</span></div>'+(c.note?'<div class="info-row"><span class="info-lbl">Note</span><span style="color:#6b6b6b">'+c.note+'</span></div>':'');document.getElementById('modal-client-detail').classList.add('open')}
const AVATAR_COLORS=['#e8f0f8','#e8f5e9','#fff3e0','#fce4ec','#ede7f6'];
function renderClients(){const q=(document.getElementById('client-search').value||'').toLowerCase();const filtered=clients.filter(c=>(c.prenom+' '+c.nom+' '+(c.email||'')).toLowerCase().includes(q));const el=document.getElementById('client-list');document.getElementById('clients-count').textContent=clients.length+' client'+(clients.length>1?'s':'')+' enregistré'+(clients.length>1?'s':'');if(!filtered.length){el.innerHTML='<div class="empty"><div class="empty-icon">👥</div>Aucun client trouvé</div>';return}const allRdvs=getVisibleRdvs();el.innerHTML=filtered.map((c,i)=>{const initials=(c.prenom?c.prenom[0]:'')+(c.nom?c.nom[0]:'');const bg=AVATAR_COLORS[i%AVATAR_COLORS.length];const nb=allRdvs.filter(r=>r.clientId===c.id).length;const typeTag=c.type==='pro'?'<span class="badge" style="background:#e8f0f8;color:#1a3a5c;margin-left:6px">Pro</span>':'';return'<div class="client-card"><div class="client-avatar" style="background:'+bg+';color:#444">'+initials+'</div><div class="client-info" onclick="showClientDetail(''+c.id+'')"><div class="client-name">'+c.prenom+' '+c.nom+typeTag+'</div><div class="client-meta">'+(c.tel||c.email||c.adresse||'Pas de coordonnées')+' · '+nb+' rdv</div></div><button class="btn-secondary" style="font-size:12px;padding:6px 12px" onclick="openEditClient(''+c.id+'')">Modifier</button></div>'}).join('')}
function renderRdvList(){const el=document.getElementById('rdv-list');const all=getVisibleRdvs().sort((a,b)=>{const da=a._vDate||a.date,db=b._vDate||b.date;return da.localeCompare(db)||a.time.localeCompare(b.time)});if(!all.length){el.innerHTML='<div class="empty"><div class="empty-icon">📅</div>Aucun rendez-vous planifié</div>';return}el.innerHTML=all.map(r=>{const cl=clients.find(c=>c.id===r.clientId);const d=r._vDate||r.date;const co=collabs.find(x=>(r.collabs||[]).includes(x.id));const col=co?.color||'#888';const chips=(r.collabs||[]).map(cid=>{const colx=collabs.find(x=>x.id===cid);return colx?'<span class="collab-chip-sm" style="background:'+alpha(colx.color,0.13)+';color:'+colx.color+'"><span style="width:6px;height:6px;border-radius:50%;background:'+colx.color+';display:inline-block"></span>'+colx.prenom+'</span>':''}).join('');return'<div class="rdv-card" onclick="openEditRdv(''+(r._pid||r.id)+'',''+d+'')"><div class="rdv-strip" style="background:'+col+'"></div><div style="flex:1;min-width:0"><div class="rdv-name">'+(cl?cl.prenom+' '+cl.nom:'Client inconnu')+'</div><div class="rdv-meta">'+fmtDate(d)+' à '+r.time+' · '+hFmt(parseFloat(r.duree||2))+' · '+(TYPES[r.type]||r.type)+'</div><div class="rdv-chips">'+chips+(r.seriesId?'<span class="badge-rec">↻ récurrent</span>':'')+'</div></div></div>'}).join('')}
function buildColorGrid(sel){selectedColor=sel||PALETTE[0];const grid=document.getElementById('color-grid');grid.innerHTML='';PALETTE.forEach(c=>{const sw=document.createElement('div');sw.className='color-swatch'+(c===selectedColor?' selected':'');sw.style.background=c;sw.onclick=()=>{selectedColor=c;buildColorGrid(c)};grid.appendChild(sw)})}
function openNewCollab(){editCollabId=null;document.getElementById('collab-modal-title').textContent='Nouveau collaborateur';document.getElementById('co-prenom').value='';document.getElementById('co-nom').value='';document.getElementById('co-role').value='employe';document.getElementById('co-password').value='';document.getElementById('co-delete-btn').style.display='none';buildColorGrid(PALETTE[collabs.length%PALETTE.length]);document.getElementById('modal-collab').classList.add('open')}
function openEditCollab(id){const c=collabs.find(x=>x.id===id);if(!c)return;editCollabId=id;document.getElementById('collab-modal-title').textContent='Modifier le collaborateur';document.getElementById('co-prenom').value=c.prenom;document.getElementById('co-nom').value=c.nom||'';document.getElementById('co-role').value=c.role||'employe';document.getElementById('co-password').value=c.password||'';document.getElementById('co-delete-btn').style.display='inline-flex';buildColorGrid(c.color);document.getElementById('modal-collab').classList.add('open')}
async function saveCollab(){const prenom=document.getElementById('co-prenom').value.trim();if(!prenom){toast('Prénom obligatoire');return}const id=editCollabId||uid();const co={id,prenom,nom:document.getElementById('co-nom').value.trim(),role:document.getElementById('co-role').value,password:document.getElementById('co-password').value.trim(),color:selectedColor};await window.DB.save('collaborateurs',id,co);toast('Collaborateur enregistré ✓');closeModal('modal-collab')}
async function deleteCollab(){if(!confirm('Supprimer ?'))return;await window.DB.remove('collaborateurs',editCollabId);toast('Supprimé');closeModal('modal-collab')}
function renderCollabs(){const grid=document.getElementById('collab-grid');if(!collabs.length){grid.innerHTML='<div class="empty"><div class="empty-icon">⭐</div>Cliquez sur + Ajouter</div>';return}const all=getVisibleRdvs();grid.innerHTML=collabs.map(c=>{const nb=all.filter(r=>(r.collabs||[]).includes(c.id)).length;const hours=all.reduce((s,r)=>(r.collabs||[]).includes(c.id)?s+parseFloat(r.duree||2):s,0);return'<div class="collab-card"><div class="collab-card-top"><div class="collab-avatar" style="background:'+alpha(c.color,0.15)+';color:'+c.color+';border-color:'+c.color+'">'+c.prenom[0]+(c.nom?c.nom[0]:'')+'</div><div><div class="collab-card-name">'+c.prenom+' '+(c.nom||'')+'</div><div class="collab-card-role">'+(c.role==='associe'?'Associée':'Employé(e)')+'</div></div><div style="margin-left:auto;width:14px;height:14px;border-radius:50%;background:'+c.color+'"></div></div><div style="border-top:1px solid var(--border);padding-top:10px;margin-top:4px"><div class="collab-stat"><span>Interventions</span><strong>'+nb+'</strong></div><div class="collab-stat"><span>Heures totales</span><strong>'+hFmt(hours)+'</strong></div></div><button class="btn-secondary" style="width:100%;margin-top:10px;font-size:12px" onclick="openEditCollab(''+c.id+'')">Modifier</button></div>'}).join('')}
function init(){window.DB.listen('clients',data=>{clients=data;if(document.getElementById('view-clients').classList.contains('active'))renderClients();renderCal()});window.DB.listen('rdvs',data=>{rdvs=data;renderCal();if(document.getElementById('view-rdvlist').classList.contains('active'))renderRdvList()});window.DB.listen('collaborateurs',data=>{collabs=data;renderCal();if(document.getElementById('view-collaborateurs').classList.contains('active'))renderCollabs()});const saved=localStorage.getItem('cp_user');if(saved){try{currentUser=JSON.parse(saved);document.getElementById('login-screen').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('user-name-display').textContent=currentUser.prenom;document.getElementById('user-avatar').textContent=currentUser.prenom[0].toUpperCase()}catch(e){}}document.getElementById('login-pass').addEventListener('keydown',e=>{if(e.key==='Enter')login()})}
window.addEventListener('load',()=>{const check=setInterval(()=>{if(window.DB){clearInterval(check);init()}},100)});